const ProfileTypeEnum = {
  CUSTOMER: "CUSTOMER",
  LEGAL_CUSTOMER: "LEGAL_CUSTOMER",
  CUSTOMER_EMPLOYEE: "CUSTOMER_EMPLOYEE",
  SELLER: "SELLER",
  LEGAL_SELLER: "LEGAL_SELLER",
  SELLER_EMPLOYEE: "SELLER_EMPLOYEE",
  SELLER_DRIVER: "SELLER_DRIVER",
  ADMIN: "ADMIN",
  FINAL_DESTINATION: "FINAL_DESTINATION",
  LEGAL_FINAL_DESTINATION: "LEGAL_FINAL_DESTINATION",
  FINAL_DESTINATION_EMPLOYEE: "FINAL_DESTINATION_EMPLOYEE",
  CITY: "CITY",
  CITY_EMPLOYEE: "CITY_EMPLOYEE",
  TAX: "TAX",
} as const;

type ProfileTypeEnum = (typeof ProfileTypeEnum)[keyof typeof ProfileTypeEnum];

export { ProfileTypeEnum };
