ALTER TABLE public.user_preferences
  ADD COLUMN IF NOT EXISTS notif_email BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notif_push BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notif_prazo BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS seg_2fa BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS seg_sessoes_unicas BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS seg_compartilhar_dados BOOLEAN NOT NULL DEFAULT true;